### ISSUE TITLE
python 3.6 support

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-datamodel#10]
When you run the bootstrap script with python 3.6 you get

```
...
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/lnielsen/envs/my-site/bin/python" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
...\
```

The problem have been reported before, but not solved as far as I know. Any chance we could get it fixed, so that instructions works for Python 3.6 as well as 3.5

**Comment by lnielsen** [comment]
Wrong repo, this is for cookiecutter-invenio-instance

**Comment by slint** [comment]
Moved over to https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/37
